apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-clone-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-clone
  template:
    metadata:
      labels:
        app: amazon-clone
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/t1m2g6a9/amazon:latest
        ports:
        - containerPort: 80

